---
title: DISCOV-Gracilaria Paper
shorttitle: DISCOV - Gracilaria
author:
  - name: Simon Oiry¹
    orcid: 0000-0001-7161-5246
    corresponding: true
    email: oirysimon@gmail.com
    roles:
      - Investigation
      - Writing
      - Data acquisition
    affiliations:
      - id: ISOMER
      - name: Institut des Substances et Organismes de la Mer, ISOMer
      - departement: Nantes Université, UR 2160
      - city: Nantes
      - country: France
  - name: Bede Ffinian Rowe Davies¹
    orcid: 0000-0001-6462-4347
    corresponding: false
    roles: 
      - Investigation
      - Data acquisition
      - Revision
    affiliations:
      - id: ISOMER
  - name: Pierre Gernez¹
    orcid: 0000-0003-2055-410X
    corresponding: false
    roles: 
      - Investigation
      - Data acquisition
      - Revision
    affiliations:
      - id: ISOMER
  - name: Laurent Barillé¹
    orcid: 0000-0001-5138-2684
    corresponding: false
    roles: 
      - Investigation
      - Data acquisition
      - Revision
    affiliations:
      - id: ISOMER
keywords:
  - Remote Sensing
  - Invasive species
  - Coastal Ecosystems
  - Biodiversity 
abstract:
  To be Written 
plain-language-summary: |
  To be written
key-points:
  To be Written
date: last-modified
citation:
  container-title: Remote Sensing of Environment
number-sections: true
notebook-links: false
editor_options: 
  chunk_output_type: console
csl: RSE.csl
---
[^1]

[^1]: Institut des Substances et Organismes de la Mer, ISOMer, Nantes Université, UR 2160, F-44000 Nantes, France

# Introduction

Coastal ecosystems are among the most dynamic and productive environments on Earth, providing ecosystem services and supporting biodiversity [@unsworth2022planetary ; @barbier2011value ; @watanabe2018introduction]. These ecosystems, spanning mangroves, salt marshes, seagrass meadows, and rocky intertidal zones, play a pivotal role in carbon sequestration, nutrient cycling, and shoreline stabilization [@liquete2013current ; @mehvar2018quantifying]. They also serve as habitats for numerous species, many of which are commercially or ecologically significant [@seitz2014ecological ; @de2023valuing]. Coastal areas are densely populated, with billions of people globally depending on their resources for livelihoods, fisheries, and tourism [@mukherjee2023coastal ; @small2003global]. However, coastal ecosystems face mounting pressures from human activities such as land reclamation, pollution, and overfishing, compounded by the impacts of climate change [@lu2018major ; @hall2019ocean]. Sea level rise, ocean acidification, and increasing storm intensity further exacerbate the vulnerability of these systems, threatening their resilience and the services they provide [@he2019climate].

One of the significant threats to coastal ecosystems is biological invasions by non-native species, which can disrupt native biodiversity and alter ecosystem functions [@krueger2018everywhere ; @capdevila2019warming ;@liu2020ocean]. *Gracilaria vermiculophylla*, an invasive red macroalga native to the northwest Pacific, exemplifies this issue. Over the last century, this species has spread extensively across temperate estuaries in North America, Europe, and other regions, facilitated by aquaculture and maritime activities [@rueness2005life ; @weinberger2008invasive ; @krueger2017genetic]. Its success as an invader stems from its tolerance to a wide range of environmental stressors, including temperature [@sotka2018combining], salinity [@weinberger2008invasive], and nutrient variability [@abreu2011nitrogen], as well as its ability to establish in soft sediment habitats traditionally devoid of macroalgae [@ramus2017invasive]. While *G. vermiculophylla* can provide some ecosystem services, such as habitat for invertebrates and juvenile fish, it often outcompetes native vegetation, alters sediment composition [@nyberg2009flora], and disrupts trophic interactions [@van2018global]. In regions like the Baltic Sea and the eastern United States, it has been documented to negatively affect native fucoids and seagrasses [@van2003reintroduction ; @thomsen2013effects]. These impacts underscore the importance of monitoring and managing the spread of *G. vermiculophylla*, particularly as climate change and anthropogenic pressures continue to facilitate biological invasions.

Remote sensing has revolutionized our ability to monitor and manage ecosystems, offering efficient and scalable methods for detecting environmental changes over large areas [@davies2024intertidal ; @davies2024sentinel ; @zoffoli2021decadal]. Among these technologies, drone-based remote sensing has emerged as a particularly promising tool for studying coastal environments [@roman2023mapping ; @roman2024mapping]. Equipped with high-resolution cameras and multispectral or hyperspectral sensors, drones can capture fine-scale spatial and spectral data, enabling researchers to identify and map vegetation, detect stress in plants, and monitor changes over time [@roman2021using ; Oiry et al. 2024]. Unlike traditional satellite imagery, drones provide the flexibility to operate in overcast conditions, achieve higher spatial resolution, and target specific areas of interest. For invasive species like *G. vermiculophylla*, drones equipped with multispectral sensors can differentiate it from native vegetation based on its unique spectral reflectance characteristics (Davies et al. 2025). This capability not only enhances detection accuracy but also reduces the time and labor associated with traditional field surveys. As the cost of drone technology continues to decrease and advancements in machine learning facilitate data analysis, drone-based remote sensing is becoming increasingly accessible and impactful for ecological research and management.

In this study, we aim to harness the potential of drone-based multispectral remote sensing to map *Gracilaria vermiculophylla* in intertidal zones.  Bla bla what are we going to do ? bla bla .